daily_missions = [
    {"mission": "Carpool with a Friend!", "points": 200},
    {"mission": "Turn the lights off when leaving the house!", "points": 100},
    {"mission": "Take public transit!", "points": 150},
    {"mission": "Walk to your destination!.", "points": 300},
    {"mission": "Use a reusable grocery bag when shopping!", "points": 200},
    {"mission": "Avoid all single-use products today!", "points": 500},
    {"mission": "Cook at home instead of going out!", "points": 200},
    {"mission": "Upcycle something!", "points": 750},
    {"mission": "Plant a tree!", "points": 3000},
    {"mission": "Limit your shower to 5 minutes!", "points": 150},
    {"mission": "Hang your clothes to dry instead of using a drying machine!", "points": 300},
    {"mission": "Lower the temperature (in the winter) or Raise the temperature (in the summer)!", "points": 300},
    {"mission": "Change your incandescent light bulbs to LED bulbs!", "points": 1000},
    {"mission": "Buy second-hand clothes instead of new clothes!", "points": 1000},
    {"mission": "Lower the temperature (in the winter) or Raise the temperature (in the summer)!", "points": 300},
    {"mission": "Do not waste any food today!", "points": 250},
    {"mission": "Unplug any appliances you are not using!", "points": 400},
    {"mission": "Buy organic groceries today!", "points": 500},
    {"mission": "Start a garden!", "points": 5000},
    {"mission": "Go to the farmer market instead of the grocery store!", "points": 700},
    {"mission": "Pick up some liter if you see any!", "points": 300},
]